- id: '1660577511317'
  alias: Polling Renault
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /20
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
      - sensor.gj468rk_battery_autonomy
      - sensor.gj468rk_battery_available_energy
      - sensor.gj468rk_battery_level
      - binary_sensor.gj468rk_charging
      - sensor.gj468rk_charging_remaining_time
      - device_tracker.gj468rk_location
      - sensor.gj468rk_mileage
      - sensor.gg085jj_battery_autonomy
      - sensor.gg085jj_battery_level
      - binary_sensor.gg085jj_charging
      - sensor.gg085jj_battery_available_energy
      - sensor.gg085jj_charging_remaining_time
      - device_tracker.gg085jj_location
      - sensor.gg085jj_mileage
      - binary_sensor.gg085jj_plugged_in
  mode: single
- id: '1662839324434'
  alias: Remplissage Piscine
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.vanne
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: input_number.set_value
    data_template:
      value: '{{ (states(''input_number.temps_remplissage_piscine'') | int) * 60 }}'
      entity_id: input_number.elapsed_remplissage_piscine
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.decompte_remplissage_piscine
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.mode_piscine
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.electrolyseur
  - delay:
      minutes: '{{ states(''input_number.temps_remplissage_piscine'') | int }}'
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.vanne
  - service: script.notif_google_home
    data:
      message: Le remplissage de la piscine est terminé
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.mode_piscine
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.decompte_remplissage_piscine
  mode: single
- id: '1662898775387'
  alias: Crepuscule ON Exterieur
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.guirlande
      - switch.pilier
      - switch.jardin_est
  mode: single
- id: '1662899844224'
  alias: Veilleuse Gabriel ON
  description: ''
  trigger:
  - platform: time
    at: '20:30:00'
  condition: []
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 0
      - 134
      - 255
      brightness_pct: 24
    target:
      entity_id: light.yeelight_gabriel
  mode: single
- id: '1663429217444'
  alias: Piscine
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /10
  - platform: state
    entity_id:
    - input_boolean.mode_piscine
  - platform: state
    entity_id:
    - binary_sensor.cycle_piscne
  condition:
  - condition: state
    entity_id: input_boolean.mode_piscine
    state: 'on'
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.cycle_piscne
      state: 'on'
    then:
    - if:
      - condition: state
        entity_id: switch.pompe_switch_0
        state: 'off'
      then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.pompe_switch_0
    - if:
      - condition: state
        entity_id: input_boolean.saison_piscine
        state: 'on'
      then:
      - delay:
          hours: 0
          minutes: 0
          seconds: 15
          milliseconds: 0
      - if:
        - condition: and
          conditions:
          - condition: state
            entity_id: switch.electrolyseur
            state: 'off'
          - condition: state
            entity_id: switch.pompe_switch_0
            state: 'on'
          - condition: state
            entity_id: input_boolean.mode_piscine
            state: 'on'
        then:
        - service: switch.turn_on
          data: {}
          target:
            entity_id: switch.electrolyseur
    else:
    - service: switch.turn_off
      data: {}
      target:
        entity_id:
        - switch.pompe_switch_0
        - switch.electrolyseur
  mode: single
- id: '1663517344914'
  alias: Reveil Tablette
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_haut
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.wake_up_tablet
  mode: single
- id: '1663519278701'
  alias: Notification Poubelle
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: calendar.poubelles
    state: 'on'
  action:
  - service: script.notif_google_home
    data:
      message: Il faut sortir la poubelle {{ state_attr('calendar.poubelles', 'message')
        }}
  mode: single
- id: '1663520952657'
  alias: Notification Charge Zoe
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.gg085jj_charge_state
  condition: []
  action:
  - if:
    - condition: state
      entity_id: sensor.gg085jj_charge_state
      state: not_in_charge
    then:
    - service: script.notif_telegram
      data:
        message: 'La charge de la Zoe est terminée : {{states.sensor.gg085jj_battery_level.state}}%'
    else:
    - service: script.notif_telegram
      data:
        message: 'La charge de la Zoe est commencé : {{states.sensor.gg085jj_battery_level.state}}%'
  mode: single
- id: '1663953216583'
  alias: Decompte Remplissage Piscine
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /1
  condition: []
  action:
  - service: input_number.decrement
    data: {}
    target:
      entity_id: input_number.elapsed_remplissage_piscine
  mode: single
- id: '1664035079801'
  alias: Arrosage
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.arrosage_ce_soir
      state: 'on'
    then:
    - if:
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.arrosage_type
          state: Tout
        - condition: state
          entity_id: input_select.arrosage_type
          state: Sprinkler
      then:
      - service: input_number.set_value
        data:
          value: 3
        target:
          entity_id: input_number.temps_arrosage
      - service: automation.turn_on
        data: {}
        target:
          entity_id: automation.decompte_arrosage
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.sprinkler
      - delay:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.sprinkler
      - service: automation.turn_off
        data: {}
        target:
          entity_id: automation.decompte_arrosage
    - if:
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.arrosage_type
          state: Tout
        - condition: state
          entity_id: input_select.arrosage_type
          state: Goutte-à-goutte
      then:
      - service: input_number.set_value
        data:
          value: 20
        target:
          entity_id: input_number.temps_arrosage
      - service: automation.turn_on
        data: {}
        target:
          entity_id: automation.decompte_arrosage
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.goutte
      - delay:
          hours: 0
          minutes: 20
          seconds: 0
          milliseconds: 0
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.goutte
      - service: automation.turn_off
        data: {}
        target:
          entity_id: automation.decompte_arrosage
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.arrosage_hier
    else:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.arrosage_hier
  mode: single
- id: '1664036043639'
  alias: Decompte Arrosage
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /1
  condition: []
  action:
  - service: input_number.decrement
    data: {}
    target:
      entity_id: input_number.elapsed_arrosage
  mode: single
- id: '1664304010323'
  alias: Notification Seche-Linge
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.seche_linge_en_marche
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.seche_linge_en_marche
      state: 'on'
    then:
    - service: script.notif_google_home
      data:
        message: Le sèche-linge a démarré
    else:
    - service: script.notif_google_home
      data:
        message: Le sèche-linge a terminé
  mode: single
- id: '1664402305968'
  alias: Renew SSL Certificate
  description: ''
  trigger:
  - platform: time
    at: 03:00:05
  condition:
  - condition: numeric_state
    entity_id: sensor.s_cert_exiry_d
    below: 30
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: hassio.addon_restart
    data:
      addon: core_nginx_proxy
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: homeassistant.restart
    data: {}
  mode: single
- id: '1664560056333'
  alias: Alerte Intrusion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.door_window_sensor_158d00024e4b12
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.presence_haut
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.presence_bas
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.enable_alarm
      state: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30
    - condition: state
      entity_id: binary_sensor.somebody_home
      state: 'off'
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - if:
    - condition: state
      entity_id: input_boolean.enable_alarm
      state: 'on'
    then:
    - service: script.notif_google_home
      data:
        bypass: true
        message: Vous avez 30 secondes pour désactiver l'alarme
    - delay:
        hours: 0
        minutes: 0
        seconds: 10
        milliseconds: 0
    - if:
      - condition: state
        entity_id: input_boolean.enable_alarm
        state: 'on'
      then:
      - service: script.notif_google_home
        data:
          bypass: true
          message: Vous avez 20 secondes pour désactiver l'alarme
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - if:
        - condition: state
          entity_id: input_boolean.enable_alarm
          state: 'on'
        then:
        - service: script.notif_google_home
          data:
            bypass: true
            message: Vous avez 10 secondes pour désactiver l'alarme
        - delay:
            hours: 0
            minutes: 0
            seconds: 10
            milliseconds: 0
        - if:
          - condition: state
            entity_id: input_boolean.enable_alarm
            state: 'on'
          then:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.intrusion_detected
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.yeelight_plafonnier
          - service: switch.turn_on
            data: {}
            target:
              entity_id:
              - switch.cabane
              - switch.cheminee
              - switch.guirlande
              - switch.jardin_est
              - switch.pilier
              - switch.poulailler
              - switch.salon
          - service: script.notif_telegram
            data:
              message: ALERTE INTRUSION !
          - repeat:
              count: '3'
              sequence:
              - service: script.notif_google_home
                data:
                  bypass: true
                  message: Attention ! Alerte intrusion ! Les services de sécurité
                    ont été prévenus
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 10
                  milliseconds: 0
          - repeat:
              count: '3'
              sequence:
              - service: button.press
                data: {}
                target:
                  entity_id: button.ring_your_phone
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 10
                  milliseconds: 0
  mode: single
- id: '1664570844806'
  alias: Update Gandi DNS
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.livebox_fibre_wan_status
    attribute: wan_ipaddress
  condition: []
  action:
  - service: rest_command.update_gandi
    data: {}
  mode: single
- id: '1665480949706'
  alias: Crepuscule OFF 1
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: +01:00:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.guirlande
  mode: single
- id: '1665481009768'
  alias: Crepuscule OFF 2
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: +02:00:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.jardin_est
      - switch.pilier
  mode: single
- id: '1671473882028'
  alias: Push Config to GitHub
  description: ''
  trigger:
  - platform: time
    at: '23:23:23'
  condition: []
  action:
  - service: shell_command.ha_gitpush
    data: {}
  mode: single
- id: '1673192794387'
  alias: Screenshot Cam
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /2
  condition: []
  action:
  - service: shell_command.copy_latest_cam_south
    data: {}
  - service: shell_command.copy_latest_cam_north
    data: {}
  mode: single
- id: '1673192910247'
  alias: Clean Cam Screenshots
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /30
  condition: []
  action:
  - service: shell_command.clean_cams
    data: {}
  mode: single
- id: '1682928756541'
  alias: Veilleuse Gabriel OFF
  description: ''
  trigger:
  - platform: time
    at: 07:30:00
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.yeelight_gabriel
  mode: single
- id: '1682929018692'
  alias: Crepuscule OFF ALL
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.cheminee
      - switch.pilier
      - switch.guirlande
      - switch.jardin_est
      - switch.salon
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.yeelight_plafonnier
  mode: single
- id: '1698836134725'
  alias: Notification Tempo
  description: ''
  trigger:
  - platform: time
    at: '20:15:00'
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.rte_tempo_prochaine_couleur
      state: Bleu
  action:
  - service: script.notif_google_home
    data:
      message: Information Tempo. Demain, journée {{ states.sensor.rte_tempo_prochaine_couleur.state
        }}
  mode: single
- id: '1698837169057'
  alias: Tempo
  description: ''
  trigger:
  - platform: time
    at: sensor.rte_tempo_prochaine_couleur_changement
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - if:
    - condition: state
      entity_id: sensor.rte_tempo_couleur_actuelle
      state: Rouge
    then:
    - data:
        stop_actions: true
      target:
        entity_id:
        - automation.piscine
        - automation.crepuscule
      action: automation.turn_off
    - data: {}
      action: switch.turn_off
      target:
        entity_id: switch.seche_linge_switch_0
    else:
    - data: {}
      target:
        entity_id:
        - automation.piscine
        - automation.crepuscule
      action: automation.turn_on
    - data: {}
      action: switch.turn_on
      target:
        entity_id: switch.seche_linge_switch_0
  mode: single
- id: '1698842284018'
  alias: Crepuscule ON Interieur
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.cheminee
      - switch.salon
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.yeelight_plafonnier
  mode: single
- id: '1698956706914'
  alias: Activation Alarme
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.somebody_home
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d00024e4b12
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.enable_alarm
  - service: script.notif_telegram
    data:
      message: Alarme activée automatiquement
  - service: browser_mod.navigate
    data:
      path: /lovelace/1
    target:
      entity_id:
      - media_player.0328af0c_cc17ac79
      - media_player.c3cc03f1_cb97c73a
  mode: single
- id: '1698957606433'
  alias: Desactivation Alarme
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.somebody_home
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.enable_alarm
      - input_boolean.intrusion_detected
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: browser_mod.navigate
    data:
      path: /lovelace/0
    target:
      entity_id:
      - media_player.0328af0c_cc17ac79
      - media_player.c3cc03f1_cb97c73a
  mode: single
- id: '1715105932266'
  alias: iOS Portail
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: open_portal
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.portail
  mode: single
