homeassistant:
  packages: !include_dir_named include
  allowlist_external_dirs: [/config/]
  internal_url: http://192.168.1.186:8123
  external_url: https://biot.questroy.com:18123

lovelace:
  mode: yaml #use ui-lovelace.yaml
  resources: #hacs
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module 
    - url: /local/custom_icons.js?v=06112023
      type: module
    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module
    - url: /hacsfiles/lovelace-badge-card/badge-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/restriction-card/restriction-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
      type: module
    - url: /hacsfiles/clock-weather-card/clock-weather-card.js
      type: module
    - url: /hacsfiles/lovelace-more-info-card/more-info-card.js
      type: module
    - url: /local/font.css
      type: css

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
    cache: true
    time_memory: 57600
    language: 'fr'
    #base_url: !secret tts_base_url
    service_name: google_say

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret http_proxy_1
    - !secret http_proxy_2
    - !secret http_proxy_3
    - !secret http_proxy_4
    - !secret http_proxy_5
    - !secret http_proxy_6
    - !secret http_proxy_7

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

media_player:
  - platform: liveboxtvuhd
    name: Livebox
    host: !secret ip_livebox_tv
    port: !secret port_livebox_tv
    scan_interval: 30
    country: france
  - platform: lg_netcast
    host: !secret ip_tv
    access_token: !secret lg_pairing_key
    name: LG TV

telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret id_telegram_hugo
      - !secret id_telegram_andrea

notify:
  - name: Telegram Andrea
    platform: telegram
    chat_id: !secret id_telegram_andrea

  - name: Telegram Hugo
    platform: telegram
    chat_id: !secret id_telegram_hugo

device_tracker:
  - platform: ping_arp
    count: 5
    scan_interval: 30
    iface: end0
    hosts:
      hugo_mob: !secret ip_hugo_mob
      andrea_mob: !secret ip_andrea_mob
      lily_mob: !secret ip_lily_mob
      gabriel_mob: !secret ip_gabriel_mob

rest_command:
  update_gandi:
    url: !secret gandi_url
    method: put
    content_type: application/json
    headers:
      authorization: !secret gandi_authorization
    payload: '{"rrset_values":["{{ state_attr("binary_sensor.wan_status", "wan_ipaddress") }}"],"rrset_ttl":300}'

shell_command:
  ha_gitpush: /bin/bash /config/shell_commands/ha_gitpush.sh
  copy_latest_cam_north: /bin/bash /config/shell_commands/copy_cam_north.sh
  copy_latest_cam_south: /bin/bash /config/shell_commands/copy_cam_south.sh
  clean_cams: /bin/bash /config/shell_commands/clean_cams.sh

google_assistant:
  project_id: friday-658fd
  report_state: true
  expose_by_default: false
  service_account:
    private_key: !secret google_private_key
    client_email: !secret google_client_email
  entity_config:
    switch.portail:
      name: Portail
    script.informations_tempo:
      name: Informations Tempo

command_line: !include command_line.yaml

frontend:
  themes: !include_dir_merge_named themes
