debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws:
  enable: false
  ssl: true
  token: HOME_ASSISTANT_TOKEN_GENERATE_IN_PROFILE_TABS_(BOTTOM)
  url: myhomeassistant.domain.fr
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: myelectricaldata
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: false
  hostname: mosquitto
  password: null
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: null
myelectricaldata:
  '25979305334360':
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2021-06-01'
    consumption_max_date: '2021-06-01'
    consumption_max_power: 'true'
    consumption_price_base: '0.145907'
    consumption_price_hc: '0.124364'
    consumption_price_hp: '0.164915'
    enable: 'true'
    name: Maison
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00
    offpeak_hours_6: 22H00-6H00
    plan: Tempo
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: '2021-06-01'
    production_max_date: '2021-06-01'
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: pdd-zZn5KSl9rfVhDyj4iBx-UvjlN4mw17CEn4Ab8FQ=
port: 5000
ssl:
  certfile: ''
  gateway: true
  keyfile: ''
tempo:
  enable: true
wipe_influxdb: false
