binary_sensor:

  - platform: group
    name: "Network pings"
    all: true
    entities:
      - binary_sensor.camera_nord
      - binary_sensor.camera_porte
      - binary_sensor.camera_sud
      - binary_sensor.gateway_xiaomi
      - binary_sensor.imprimante
      - binary_sensor.ap_exterieur
      - binary_sensor.ap_salon
      - binary_sensor.shelly_cheminee
      - binary_sensor.shelly_jardin_sud
      - binary_sensor.shelly_electrolyseur
      - binary_sensor.shelly_sprinkler
      - binary_sensor.shelly_drip
      - binary_sensor.shelly_guirlande
      #- binary_sensor.shelly_jardin_nord
      - binary_sensor.shelly_pilier
      - binary_sensor.yeelight_plafonnier
      - binary_sensor.shelly_pompe
      - binary_sensor.shelly_portail
      - binary_sensor.shelly_salon
      - binary_sensor.shelly_seche_linge
      - binary_sensor.shelly_spot
      #- binary_sensor.shelly_chauffage_lily
      - binary_sensor.shelly_vanne
      - binary_sensor.tablette_murale
      - binary_sensor.thermostat
      - binary_sensor.yeelight_gabriel
      - binary_sensor.rpi_4
      - binary_sensor.google_home
      - binary_sensor.sonos
      - binary_sensor.ap_bureau
      - binary_sensor.ap_garage
      - binary_sensor.ap_lily
      - binary_sensor.shelly_chargeur
      - binary_sensor.shelly_camera
      - binary_sensor.yeelight_tempo
      - binary_sensor.ulanzi
