sensor:

  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  - platform: statistics
    name: "Pluiviométrie Last 24h"
    entity_id: sensor.biot_daily_precipitation
    state_characteristic: total
    max_age:
      hours: 24

  - platform: template
    sensors:
      s_cert_exiry_d:
        friendly_name: 'Cert Expiry'
        value_template: >
          {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_external')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int }}
        unit_of_measurement: 'days'
      test_pluie:
        friendly_name: 'Test Pluie'
        value_template: >
          {{ states("sensor.pluiviometrie_last_24h") | float(0) }}
        unit_of_measurement: 'mm'

  - platform: rest
    name: Gandi IP
    resource: !secret gandi_url
    method: GET
    headers:
      authorization: !secret gandi_authorization
    value_template: "{{ value_json.rrset_values[0] }}"

  - platform: 'gazpar'
    name: 'gazpar'
    username: !secret grdf_user
    password: !secret grdf_pwd
    pce_identifier: !secret grdf_pce
    tmpdir: '/tmp'
    scan_interval: '08:00:00'