sensor:

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: /media/ext
      - type: processor_temperature
      - type: memory_use_percent
      - type: load_5m
      - type: load_1m
      - type: processor_use

  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  - platform: statistics
    name: "Pluiviométrie Last 24h"
    entity_id: sensor.biot_daily_precipitation
    state_characteristic: total
    max_age:
      hours: 24

  - platform: template
    sensors:
      s_cert_exiry_d:
        friendly_name: 'Cert Expiry'
        value_template: >
          {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_external')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int }}
        unit_of_measurement: 'days'
      test_pluie:
        friendly_name: 'Test Pluie'
        value_template: >
          {{ states("sensor.pluiviometrie_last_24h") | float(0) }}
        unit_of_measurement: 'mm'
      niveau_encre_noire_preserved:
        friendly_name: Niveau Encre Noire
        unit_of_measurement: '%'
        icon_template: mdi:water
        value_template: >-
          {% if states('sensor.canon_ts5100_series_black') not in ['unknown', 'unavailable'] and (states('sensor.canon_ts5100_series_black') | int) > 0 %}
            {{ states('sensor.canon_ts5100_series_black') }}
          {% else %}
            {{ states('sensor.niveau_encre_noire_preserved') }}
          {% endif %}
      niveau_encre_couleur_preserved:
        friendly_name: Niveau Encre Couleur
        unit_of_measurement: '%'
        icon_template: mdi:water
        value_template: >-
          {% if states('sensor.canon_ts5100_series_color') not in ['unknown', 'unavailable'] and (states('sensor.canon_ts5100_series_color') | int) > 0 %}
            {{ states('sensor.canon_ts5100_series_color') }}
          {% else %}
            {{ states('sensor.niveau_encre_couleur_preserved') }}
          {% endif %}
      temp_piscine_preserved:
        friendly_name: Température Piscine Réelle
        unit_of_measurement: '°C'
        icon_template: mdi:thermometer
        value_template: >-
          {% if states('sensor.spot_temp_temperature') not in ['unknown', 'unavailable'] and states('switch.pompe_switch_0') == 'on' %}
            {{ states('sensor.spot_temp_temperature') }}
          {% else %}
            {{ states('sensor.temp_piscine_preserved') }}
          {% endif %}

  - platform: rest
    name: Gandi IP
    resource: !secret gandi_url
    method: GET
    headers:
      authorization: !secret gandi_authorization
    value_template: "{{ value_json.rrset_values[0] }}"
